import { Geist, Geist_Mono } from "next/font/google";
import "../../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
  <html lang="zxx">
    <head>
      <link rel="shortcut icon" href="/images/favicon.png" />
      <meta name="theme-name" content="Pinwheel" />
      <meta name="msapplication-TileColor" content="#000000" />
      <meta
        name="theme-color"
        media="(prefers-color-scheme: light)"
        content="#fff"
      />
      <meta
        name="theme-color"
        media="(prefers-color-scheme: dark)"
        content="#000"
      />
      <meta name="generator" content="gulp" />
      <meta httpEquiv="Content-Type" content="text/html; charset=UTF-8" />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=5"
      />
      <title>Pinwheel-tailwind</title>

      <meta name="robots" content="" />

      <meta name="description" content="meta description" />

      <meta name="author" content="{config.metadata.meta_author}" />
      <meta property="og:title" content="" />

      <meta property="og:description" content="" />
      <meta property="og:type" content="website" />
      <meta property="og:url" content="/" />
      <meta name="twitter:title" content="" />

      <meta name="twitter:description" content="" />

      <meta property="og:image" content="" />

      <meta name="twitter:image" content="" />
      <meta name="twitter:card" content="summary_large_image" />

      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />

      <link
        href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap"
        rel="stylesheet"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Merriweather:wght@700;900&display=swap"
        rel="stylesheet"
      />


      <link rel="stylesheet" href="/plugins/swiper/swiper-bundle.css" />

      <link rel="stylesheet" href="/plugins/font-awesome/v6/brands.css" />
      <link rel="stylesheet" href="/plugins/font-awesome/v6/solid.css" />
      <link rel="stylesheet" href="/plugins/font-awesome/v6/fontawesome.css" />

      <link href="/styles/main.css" rel="stylesheet" />
    </head>
    <body>
      {children}
    </body>
  </html>
  );
}
